# Generated by Django 4.0 on 2023-06-14 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='is_public',
            field=models.BooleanField(default=True, help_text='public ads will be displayed', verbose_name='is piblic'),
        ),
    ]
